<?php

use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function test_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        // When viewing a revision $node will be numeric.
        // @see https://www.drupal.org/node/2495703
        if (is_numeric($node)) {
            $node = Node::load($node);
        }
        if ($node instanceof NodeInterface) {
            array_splice($suggestions, 1, 0, 'page__node__' . $node->bundle());
        }
    }
}

/**
 * Implements template_preprocess_node
 *
 * Add template suggestions and classes
 */
function test_preprocess_node(&$variables) {
    // Add node--node_type--view_mode.html.twig suggestions
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['elements']['#node']->bundle() . '__' . $variables['view_mode'];

    // Add node--view_mode.html.twig suggestions
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['view_mode'];

    // Add a class for the view mode.
//    if (!$variables['teaser']) {
//        $variables['content_attributes']['class'][] = 'view-mode-' . $variables['view_mode'];
//    }
//
//    $variables['title_attributes']['class'][] = 'node-title';
}

/**
 * Implements hook_preprocess_block()
 */
function test_preprocess_block(&$variables) {
    // Convenience variable for block headers.
    $title_class = &$variables['title_attributes']['class'];

    // Generic block header class.
    $title_class[] = 'block-title';

    $region = isset($variables['configuration']['region']) ? $variables['configuration']['region'] : '';

    if ($region == 'header') {
        $title_class[] = 'visually-hidden';
    }

    // Add a unique class for each block for styling.
    if (isset($variables['attributes']['id'])) {
        $variables['attributes']['class'][] = $variables['attributes']['id'];
    }

    switch ($region) {
        // Add a striping class
        case 'sidebar_first':
        case 'sidebar_second':
            #$variables['attributes']['class'][] = 'block-' . $variables['zebra'];
            break;

        case 'header':
            $variables['attributes']['class'][] = 'header';
            break;

        default;
    }
}
